#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"

SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14}

LOGS_FOLDER="/home/ec2-user/shellscript.logs"
LOG_FILE=$(echo $0 | awk -F "/" ${print $NF} | cut -d "." -f1)
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
USER=$(logname)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"

sudo mkdir -p /home/ec2-user/shellscript.logs
echo "Filename : $0"

USAGE(){
     echo -e "$R USAGE:: $N sh backup_files <source_dir> <Dest_dir> <DAYS(optional)>"
    exit 1
}

if [ $# -lt 2 ]
then
    USAGE
fi

if [ ! -d $SOURCE_DIR ]
  then
      echo -e "$R $SOURCE_DIR does not exist.....please check"$N
      exit 1
fi

if [ ! -d $DEST_DIR ]
  then
     echo -e "$R $DEST_DIR does not exist....please check"$N
     exit 1
fi

FILES=$(find $SOURCE_DIR -name "*.log" -mtime +$DAYS)


if [ -n "$FILES" ]
   then
      echo "files are: $FILES"
      ZIP_FILE="$DEST_DIR/app-logs-$TIMESTAMP.zip"
      find $SOURCE_DIR -name "*.log" -mtime +$DAYS | zip -@ "$ZIP_FILE"
      if [ -f $ZIP_FILE ]
        then
         echo "Successfully created zip file"
         while read -r file     &>>LOG_FILE_NAME
          do
            echo "deleting file: $file"  
            rm -rf $file
          done <<< $FILES
       else
         echo -e "$R ERROR:: $N failed to create zip file"
         exit 1
      fi

    else
      echo "no files found from older then $DAYS"
fi

