#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"

SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14}

LOGS_FOLDER="/home/ec2-user/shellscript.logs"
LOG_FILE=$(echo $0 | cut -d "." -f1)
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
USER=$(logname)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"

sudo mkdir -p /home/ec2-user/shellscript.logs

USAGE(){
     echo -e "$R USAGE:: $N sh backup_files <source_dir> <Dest_dir> <DAYS(optional)>"
    
}

if [ $# -lt 2 ]
then
    USAGE
fi

while read -r file
do
  echo "deleting file: $file"
done <<< $LOGS_FOLDER
