#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"

sudo mkdir -p /var/log/mysql_logs

SOURCE_DIR="/home/ec2-user/app_logs"

LOGS_FOLDER="/var/log/mysql_logs"
LOG_FILE=$(echo $0 | cut -d "." -f1)
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
USER=$(logname)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"



FUNCTION(){
    if [ $1 -ne 0 ]
     then
       echo -e "$2.....$R Failure"$N
       exit 2
     else
       echo -e "$2.....$G Success"$N
    fi
}

FILES_TO_DELETE=$(find $SOURCE_DIR -name "*.log" -mtime +14)
echo "files to be deleted: $FILES_TO_DELETE"

while read -r file
do
echo "deleting file: $file"

done <<< $FILES_TO_DELETE