#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
echo "Error: you're not sudo mode, get sudo access and proceed"
fi

dnf list installed mysql
 if [ $? -ne 0 ]
    then 
       dnf install mysql -y
       if [ $? -ne 0 ]
       then
           echo "mysql installation ....failure"
        else
            echo "mysql installation.....successfully"
        fi
fi