#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
echo "Error: you're not sudo mode, get sudo access and proceed"
exit 1
fi

dnf list installed mysql
 if [ $? -ne 0 ]
       dnf install mysql -y
       if [ $? -ne 0 ]
       then
           echo "mysql installation ....failure"
           exit 1
        else
            echo "mysql installation.....successfully"
        fi