#!/bin/bash

USERID=$(id -u)
FUNCTION(){
    if [ $1 -ne 0 ]
         then
           echo "$2 ....failure"
           exit 1
        else
            echo "$2 .....successfully"
       fi   
}
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"
if [ $USERID -ne 0 ]
then
echo "Error: you're not sudo mode, get sudo access and proceed"
exit 1
fi

for package in $@
do
    dnf list installed $package
    if [ $? -ne 0 ]
      then
      dnf install $package -y
      FUNCTION $? "Installing $Package"
    else
      echo -e "$package is already $B...Installed"$N
    fi
done
