#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"

LOGS_FOLDER="/var/log/shellscript_logs"
LOG_FILE=$(echo $0 | cut -d "." -f1 )
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
USER=$(logname)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"
FUNCTION(){
    if [ $1 -ne 0 ]
         then
           echo -e "$2....$R Failure"$N
           exit 1
        else
            echo -e "$2.....$G Success"$N
       fi   
}

if [ $USERID -ne 0 ]
then
echo "Error: you're not sudo mode, get sudo access and proceed"
exit 1
fi

for package in $@
do
  dnf list installed $package &>>LOG_FILE_NAME
  if [ $? -ne 0 ]
  then
      dnf install $package -y &>>LOG_FILE_NAME
      FUNCTION $? "Installing $package"
   else
      echo -e "$package already $B Installed"$N   
  fi    
done