#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
echo "ERROR : you must need sudo access for this process"

fi

dnf install mysqll -y

if [ $? -ne 0 ]
then
echo "mysql installation.....Failure"

else
echo "mysql installation.....success"
fi

dnf install git -y
exit 3
dnf install nginx -y
