#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"


LOGS_FOLDER="/var/log/frontend_logs"
LOG_FILE=$(echo $0 | cut -d "." -f1 )
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
USER=$(logname)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"

FUNCTION(){
    if [ $1 -ne 0 ]
         then
           echo -e "$2....$R Failure"$N
           exit 1
        else
            echo -e "$2.....$G Success"$N
       fi   
}

if [ $USERID -ne 0 ]
then
echo "Error: you're not sudo mode, get sudo access and proceed"
exit 1
fi

mkdir -p $LOGS_FOLDER

echo "$TIMESTAMP" &>>$LOG_FILE_NAME
echo "$USER"  &>>$LOG_FILE_NAME

dnf install nginx -y   &>>$LOG_FILE_NAME
FUNCTION $? "Installation nginx"

systemctl enable nginx  &>>$LOG_FILE_NAME
FUNCTION $? "enabling nginx"

systemctl start nginx  &>>$LOG_FILE_NAME
FUNCTION $? "starting nginx"

rm -rf /usr/share/nginx/html/*  &>>$LOG_FILE_NAME
FUNCTION $? "Removing exesting code"

curl -o /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip &>>$LOG_FILE_NAME
FUNCTION $? "download nginx code"

cd /usr/share/nginx/html
FUNCTION $? "moving download code"

unzip /tmp/frontend.zip   &>>$LOG_FILE_NAME
FUNCTION $? "unzip code"

cp /home/ec2-user/shell-scrict/expense_project_shell/expense.conf /etc/nginx/default.d/expense.conf   
FUNCTION $? "copied expense config"

sytemctl restart nginx   &>>$LOG_FILE_NAME
FUNCTION "restarted nginx"





